### ISSUE TITLE
Put your bug or request title here

### ISSUE THREAD

**Issue by kcohane00** [rich-at-thinkful/auditor-issues#5]
- [x ] Bug
- [ ] Feature request
- [ ] Other

Ankita Vaid in DMI 7 1.11.2021 has a 0 completion for Immersion, but I checked her dashboard and it was completed.

**Comment by MrSkinny** [comment]
Hey @kcohane00 If you click the dropdown on the dashboard to look at individual checkpoints, does the data match?  The problem is the Auditor only counts the checkpoints completed and displays it, while the Dashboard apparently has some other kind of input as to whether a module is completed, even if its checkpoints are not.

I'd argue the Auditor is correct and you should direct the student to make sure to mark the checkpoint complete.
